apiVersion: v1
kind: Template
labels:
  application: pipeline
metadata:
  name: pipeline
parameters:
- description: Petstore application source URI
  displayName: Petstore Source URI
  name: PS_GIT_URI
  required: true
  value: https://github.com/eformat/ps.git
- description: Petstore application source reference
  displayName: Petstore Source Ref
  name: PS_GIT_REF
  required: true
  value: master
- name: GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  description: Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: GENERIC_WEBHOOK_SECRET
  displayName: Generic Webhook Secret,
  description: A secret string used to configure the Generic webhook.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: pipeline
    name: pipeline
  spec:
    runPolicy: Serial
    source:
      secrets: null
      type: "Git"
      git:
        uri: ${PS_GIT_URI}#${PS_GIT_REF}
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: "PS_GIT_URI"
          value: ${PS_GIT_URI}
        - name: "PS_GIT_REF"
          value: ${PS_GIT_REF}
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
    - github:
        secret: ${GITHUB_TRIGGER_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_TRIGGER_SECRET}
      type: Generic